#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
UI Module - 重新导出自 cli.components.ui

🚪 Access - 💬 CLI - UI 组件

此文件已迁移到 cli/components/ui.py，此文件提供向后兼容。
"""

# 重新导出自新位置
from common.terminal.ui import (
    Colors,
    Theme,
    should_use_color,
    supports_ansi,
    enable_ansi_support,
    get_terminal_width,
    get_terminal_height,
    strip_ansi,
    HEX_AVOCADO,
    HEX_AVOCADO_BRIGHT,
    HEX_AVOCADO_DIM,
    RGB_AVOCADO,
    RGB_AVOCADO_BRIGHT,
    RGB_AVOCADO_DIM,
    print_info,
    print_success,
    print_warning,
    print_error,
    print_header,
    print_divider,
    print_step,
    print_substep,
    print_end_step,
    print_box,
    print_table_row,
    print_spinner,
    Spinner,
    prompt,
    prompt_yes_no,
    prompt_choice,
    HAS_RICH,
    status_bar,
    StatusBar,
    print_banner,
    print_banner_simple,
    print_prompt,
    print_header_text,
    print_menu,
    print_config_item,
    print_list,
    print_agent_response,
    print_status_bar,
    print_user_input,
    print_provider_list,
    print_setup_complete,
    print_rich_table,
    print_rich_panel,
    print_rich_progress,
    print_rich_success,
    print_rich_error,
    print_rich_warning,
    print_rich_info,
    format_round,
)

__all__ = [
    "Colors",
    "Theme",
    "should_use_color",
    "supports_ansi",
    "enable_ansi_support",
    "get_terminal_width",
    "get_terminal_height",
    "strip_ansi",
    "HEX_AVOCADO",
    "HEX_AVOCADO_BRIGHT",
    "HEX_AVOCADO_DIM",
    "RGB_AVOCADO",
    "RGB_AVOCADO_BRIGHT",
    "RGB_AVOCADO_DIM",
    "print_info",
    "print_success",
    "print_warning",
    "print_error",
    "print_header",
    "print_divider",
    "print_step",
    "print_substep",
    "print_end_step",
    "print_box",
    "print_table_row",
    "print_spinner",
    "Spinner",
    "prompt",
    "prompt_yes_no",
    "prompt_choice",
    "HAS_RICH",
    "status_bar",
    "StatusBar",
    "print_banner",
    "print_banner_simple",
    "print_prompt",
    "print_header_text",
    "print_menu",
    "print_config_item",
    "print_list",
    "print_agent_response",
    "print_status_bar",
    "print_user_input",
    "print_provider_list",
    "print_setup_complete",
    "print_rich_table",
    "print_rich_panel",
    "print_rich_progress",
    "print_rich_success",
    "print_rich_error",
    "print_rich_warning",
    "print_rich_info",
    "format_round",
]